# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:45:32+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class MultimediaItem(BaseModel):
    caption: Optional[str] = None
    copyright: Optional[str] = None
    format: Optional[str] = None
    height: Optional[int] = None
    subtype: Optional[str] = None
    type: Optional[str] = None
    url: Optional[str] = None
    width: Optional[int] = None


class RelatedUrl(BaseModel):
    suggested_link_text: Optional[str] = None
    url: Optional[str] = None


class Article(BaseModel):
    abstract: Optional[str] = None
    byline: Optional[str] = None
    created_date: Optional[str] = None
    des_facet: Optional[List[str]] = None
    geo_facet: Optional[List[str]] = None
    item_type: Optional[str] = None
    kicker: Optional[str] = None
    material_type_facet: Optional[str] = None
    multimedia: Optional[List[MultimediaItem]] = None
    org_facet: Optional[List[str]] = None
    per_facet: Optional[List[str]] = None
    published_date: Optional[str] = None
    related_urls: Optional[List[RelatedUrl]] = None
    section: Optional[str] = None
    short_url: Optional[str] = None
    subsection: Optional[str] = None
    thumbnail_standard: Optional[str] = None
    title: Optional[str] = None
    updated_date: Optional[str] = None
    url: Optional[str] = None


class Section(Enum):
    home = 'home'
    opinion = 'opinion'
    world = 'world'
    national = 'national'
    politics = 'politics'
    upshot = 'upshot'
    nyregion = 'nyregion'
    business = 'business'
    technology = 'technology'
    science = 'science'
    health = 'health'
    sports = 'sports'
    arts = 'arts'
    books = 'books'
    movies = 'movies'
    theater = 'theater'
    sundayreview = 'sundayreview'
    fashion = 'fashion'
    tmagazine = 'tmagazine'
    food = 'food'
    travel = 'travel'
    magazine = 'magazine'
    realestate = 'realestate'
    automobiles = 'automobiles'
    obituaries = 'obituaries'
    insider = 'insider'


class Format(Enum):
    json = 'json'
    jsonp = 'jsonp'
