# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:45:32+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import Article


class FieldFormatGetResponse(BaseModel):
    results: Optional[List[Article]] = None
