# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:45:32+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity

from models import Format, Section
from models.field_section_ import FieldFormatGetResponse

app = MCPProxy(
    description='The Top Stories API provides lists of articles and associated images by section.',
    termsOfService='http://developer.nytimes.com/tou',
    title='Top Stories',
    version='2.0.0',
    servers=[
        {'url': 'http://api.nytimes.com/svc/topstories/v2'},
        {'url': 'https://api.nytimes.com/svc/topstories/v2'},
    ],
)


@app.get(
    '/{section}.{format}',
    description=""" The Top Stories API returns a list of articles and associated images currently on the specified section.  Support JSON and JSONP.
 """,
    tags=['section_format_management'],
    security=[
        APIKeyQuery(name="api-key"),
    ],
)
def get__section__format(
    section: Section, format: Format = ..., callback: Optional[str] = None
):
    """
    Top Stories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
